name: open_filex
description: A plug-in that can call native APP to open files with string result in flutter, support iOS(UTI) / android(intent) / PC(ffi) / web(dart:html)
version: 4.6.0
homepage: https://github.com/javaherisaber/open_file

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.2

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=3.19.3"
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.crazecoder.openfile
        pluginClass: OpenFilePlugin
      ios:
        pluginClass: OpenFilePlugin
